# Generated by Django 6.0.8 on 2026-09-29 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name, e.g. "SG01-cPanel"', max_length=100)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=2087)),
                ('driver', models.CharField(choices=[('cpanel', 'cPanel/WHM'), ('cyberpanel', 'CyberPanel')], db_index=True, default='cpanel', max_length=20)),
                ('api_username', models.CharField(max_length=100)),
                ('_api_token', models.TextField(db_column='api_token', help_text='Fernet-encrypted API token/WHM hash. Use get_api_token().')),
                ('max_accounts', models.PositiveIntegerField(default=500, help_text='Maximum number of hosting accounts on this server.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nameserver_1', models.CharField(blank=True, max_length=100)),
                ('nameserver_2', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='HostingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('disk_quota_mb', models.PositiveIntegerField(help_text='Disk quota in MB. 0 = unlimited.')),
                ('bandwidth_mb', models.PositiveIntegerField(help_text='Monthly bandwidth in MB. 0 = unlimited.')),
                ('max_databases', models.PositiveIntegerField(default=10)),
                ('max_email_accounts', models.PositiveIntegerField(default=20)),
                ('max_subdomains', models.PositiveIntegerField(default=10)),
                ('max_ftp_accounts', models.PositiveIntegerField(default=5)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarterly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('semi_annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('panel_package_name', models.CharField(help_text='Exact package name as configured on the server panel.', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='hosting.server')),
            ],
            options={
                'verbose_name': 'Hosting Package',
                'verbose_name_plural': 'Hosting Packages',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='HostingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(help_text='cPanel/CyberPanel username (max 16 chars, alphanumeric).', max_length=16, unique=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('semi_annual', 'Semi-Annual (6 months)'), ('annual', 'Annual')], default='monthly', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price paid per billing cycle in platform currency (BDT).', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('failed', 'Provisioning Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message from provisioning/suspension for admin debugging.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosting_accounts', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='hosting.hostingpackage')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='hosting.server')),
            ],
            options={
                'verbose_name': 'Hosting Account',
                'verbose_name_plural': 'Hosting Accounts',
                'indexes': [models.Index(fields=['status', 'next_due_date'], name='idx_account_status_due')],
            },
        ),
    ]
