# Generated by Django 6.0.8 on 2026-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingaccount',
            name='password_encrypted',
            field=models.TextField(blank=True, db_column='password_encrypted', default='', help_text='Fernet-encrypted cPanel password. Use get_account_password().'),
        ),
        migrations.AlterField(
            model_name='hostingaccount',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly (1 Month)'), ('quarterly', 'Quarterly (3 Months)'), ('semi_annual', 'Semi-Annual (6 Months)'), ('annual', 'Annually (1 Year)'), ('biennial', 'Biennially (2 Years)'), ('triennial', 'Triennially (3 Years)')], default='monthly', max_length=15),
        ),
    ]
