# Generated by Django 6.0.8 on 2026-10-02 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='domains.domain'),
        ),
    ]
