# Generated by Django 6.0.8 on 2026-10-05 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_title', models.CharField(default='HostPro — High Performance Cloud Web Hosting & Domains', help_text='Main website title shown in search engines and social share previews.', max_length=200)),
                ('company_name', models.CharField(default='HostPro', help_text='Brand name used across navigation, invoice header, and copyright.', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Next-Gen NVMe Cloud & BDIX Hosting Platform', max_length=255)),
                ('meta_description', models.TextField(default='Premium high-speed cloud web hosting, cPanel, BDIX, LiteSpeed, and domain registration with automated provisioning and instant Bangladeshi payment gateways (bKash, Nagad, SSLCommerz).', help_text='Meta description for Google SEO and social share previews (Facebook, WhatsApp, Twitter).')),
                ('meta_keywords', models.TextField(blank=True, default='web hosting, bdix hosting, cpanel hosting, spaceship domain, bdwebs, buy domain bangladesh, bkash hosting, cheap hosting', help_text='Comma-separated SEO keywords and tags.')),
                ('logo_url', models.CharField(blank=True, default='', help_text='Custom Logo Image URL (e.g. /static/img/logo.png or https://...)', max_length=500)),
                ('favicon_url', models.CharField(blank=True, default='', help_text='Browser Tab Favicon URL', max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, default='', help_text='Social Share Banner / OG Thumbnail Image URL (1200x630 for WhatsApp / Facebook previews).', max_length=500)),
                ('whatsapp_number', models.CharField(default='8801700000000', help_text='WhatsApp Support phone number (e.g. +8801712345678 or 01712345678)', max_length=50)),
                ('support_email', models.EmailField(blank=True, default='support@webkoders.com', max_length=100)),
                ('support_phone', models.CharField(blank=True, default='+880 1700-000000', max_length=50)),
                ('office_address', models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=255)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=255)),
                ('instagram_url', models.URLField(blank=True, default='', max_length=255)),
                ('twitter_url', models.URLField(blank=True, default='', max_length=255)),
                ('telegram_url', models.URLField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site & SEO Setting',
                'verbose_name_plural': 'Site & SEO Settings',
            },
        ),
    ]
