# Generated by Django 6.0.9 on 2026-10-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='company_name',
            field=models.CharField(default='VeloHoster', help_text='Brand name used across navigation, invoice header, and copyright.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='VeloHoster — High Performance Cloud Web Hosting & Domains', help_text='Main website title shown in search engines and social share previews.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='support_email',
            field=models.EmailField(blank=True, default='support@velohoster.com', max_length=100),
        ),
    ]
