# Generated by Django 6.0.8 on 2026-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='show_hero_section',
            field=models.BooleanField(default=True, help_text='Toggle Hero Section on the Homepage.'),
        ),
    ]
