# Generated by Django 6.0.8 on 2026-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_show_hero_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='binance_pay_id',
            field=models.CharField(blank=True, default='', help_text='Binance Pay ID / Binance Email / Pay QR', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cryptomus_merchant_id',
            field=models.CharField(blank=True, default='', help_text='Cryptomus Merchant UUID from Cryptomus Dashboard', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cryptomus_payment_api_key',
            field=models.CharField(blank=True, default='', help_text='Cryptomus Payment API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usdt_bep20_wallet',
            field=models.CharField(blank=True, default='', help_text='USDT BEP-20 (BNB Smart Chain) Wallet Address', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='usdt_trc20_wallet',
            field=models.CharField(blank=True, default='', help_text='USDT TRC-20 Wallet Address (Binance / Trust Wallet)', max_length=100),
        ),
    ]
