# Generated by Django 6.0.8 on 2026-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_binance_pay_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bdt_per_usd',
            field=models.DecimalField(decimal_places=2, default=120.0, help_text='Conversion Rate: How many BDT per 1 USD (e.g. 120.00)', max_digits=10),
        ),
    ]
