# Generated by Django 6.0.8 on 2026-10-02 04:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRegistrar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name, e.g. "ResellerClub Production"', max_length=100)),
                ('driver', models.CharField(choices=[('resellerclub', 'ResellerClub'), ('namecheap', 'Namecheap'), ('mock', 'Mock / Sandbox Registrar')], db_index=True, default='mock', max_length=30)),
                ('api_user', models.CharField(help_text='Reseller ID or API User', max_length=150)),
                ('_api_key', models.TextField(db_column='api_key', help_text='Fernet-encrypted API key / Secret. Use get_api_key().')),
                ('is_sandbox', models.BooleanField(default=True, help_text='If checked, requests point to the registrar test sandbox.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default registrar for new orders')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Additional options (customer_id, client_ip, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain Registrar',
                'verbose_name_plural': 'Domain Registrars',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing Registration'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('registration_years', models.PositiveSmallIntegerField(default=1)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('nameserver_1', models.CharField(default='ns1.hostpro.bd', max_length=150)),
                ('nameserver_2', models.CharField(default='ns2.hostpro.bd', max_length=150)),
                ('nameserver_3', models.CharField(blank=True, max_length=150)),
                ('nameserver_4', models.CharField(blank=True, max_length=150)),
                ('auto_renew', models.BooleanField(default=True)),
                ('epp_code', models.CharField(blank=True, help_text='Domain EPP/Auth transfer code', max_length=100)),
                ('registrar_order_id', models.CharField(blank=True, help_text='Order reference from registrar API', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to=settings.AUTH_USER_MODEL)),
                ('registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='domains.domainregistrar')),
            ],
            options={
                'verbose_name': 'Client Domain',
                'verbose_name_plural': 'Client Domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TLDPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tld', models.CharField(help_text='e.g. .com, .net, .org, .com.bd', max_length=20, unique=True)),
                ('register_price', models.DecimalField(decimal_places=2, help_text='1-Year Registration Price in BDT', max_digits=10)),
                ('renew_price', models.DecimalField(decimal_places=2, help_text='1-Year Renewal Price in BDT', max_digits=10)),
                ('transfer_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transfer Price in BDT', max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('registrar', models.ForeignKey(blank=True, help_text='Default registrar for this TLD', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tld_prices', to='domains.domainregistrar')),
            ],
            options={
                'verbose_name': 'TLD Pricing',
                'verbose_name_plural': 'TLD Pricing Catalogue',
                'ordering': ['register_price'],
            },
        ),
    ]
