# Generated by Django 6.0.8 on 2026-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainregistrar',
            name='driver',
            field=models.CharField(choices=[('spaceship', 'Spaceship.com (Namecheap Cloud)'), ('bdwebs', 'BDWebs / WHMCS Domain Reseller'), ('resellerclub', 'ResellerClub'), ('namecheap', 'Namecheap'), ('mock', 'Mock / Sandbox Registrar')], db_index=True, default='mock', max_length=30),
        ),
    ]
